// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

/**
 * 게임 플레이 태그를 정의하는 클래스
 */
namespace DemoPlayerGameplayTag
{
    // 인풋 액션 태그
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_1);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_2);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_3);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill_4);


    // 어빌리티 태그
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Combat_Attack);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Combat_Dash);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Combat_Skill);

    // 플레이어 무기 태그
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_DimesionStaff);
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

    // 이벤트 트리거 태그
    CHARACTERSHOWCASE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Attack);

}